#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

usageAndExit(){
    echo -e "Usage: $0 [device] [mount-point]"
    echo -e "Example: $0 /dev/sdd1 /mnt/device"
    exit 1
}

# check if this script is running as root
if [ $UID -ne 0 ]; then
    echo -e "${RED}$0 must be run as root.${NC}"
    usageAndExit
fi

# check if correct number of parameters are passed to this script
if [ "$#" -ne 2 ]; then
    echo -e "${RED}Parameters missing.${NC}"
    usageAndExit
fi

# check if required packages are installed
dep_req=( cryptsetup cryptmount mount )
dep_not_found=( )
i=0
for dep in "${dep_req[@]}"
do
    q=$(dpkg-query -W -f='${Status}' ${dep} 2>/dev/null | grep -c "ok installed")
    if [ ${q} -eq 0 ]; then
        dep_not_found[$i]=${dep}
        ((i++))
    fi
done
if [ ${i} -ne 0 ]; then
    echo -e "${RED}Abort: Dependency package/s not found: ${NC}"
    printf '%s ' "${dep_not_found[@]}"
    echo ""
    exit 1
fi

mount=$1

echo -e "${GREEN}Mount point: ${mount} ${NC}"

umount ${mount}
cryptsetup luksClose crypt

echo -e "${GREEN}Device unmounted ${NC}"
