#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

if [ $UID -ne 0 ]; then
    echo -e "${RED}$0 must be run as root${NC}"
    exit 1
fi

echo -e "${GREEN}=== INSTALLING TEXLIVE PACKAGES...${NC}"
apt-get install texlive-full texmaker

echo "=== Coping custom tex library..."
cp -r ../tex/texmf $HOME
echo "=== DONE!"

echo -e "${GREEN}=== FINISH! ===${NC}"
