#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

if [ $UID -eq 0 ] ; then
    echo -e "${RED}$0 is not necessary to run this as root${NC}"
    exit 1
fi

echo -e "${GREEN}=== REQUIREMENTS: git installed and fully configured! ===${NC}"
sudo apt-get install vim
echo "=== Create home folder structure..."
mkdir ~/.vim
mkdir ~/.vim/swap
mkdir ~/.vim/backup
mkdir ~/.vim/undo
mkdir ~/.vim/bundle
mkdir ~/.vim/gobinaries
cp -r ../vim/syntax ~/.vim
cp -r ../vim/skeletons ~/.vim
cp -r ../vim/colors ~/.vim
cp -r ../vim/spell ~/.vim
cp ../vim/.vimrc ~
echo "=== vimrc file copied!!"
echo "=== Cloning Vundle plug-in manager..."
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo -e "${GREEN}=== INSTALLING PLUG-IN DEPENDENCIES...${NC}"
sudo apt-get install exuberant-ctags build-essential cmake python-dev
echo -e "${GREEN}=== VIM setup complete! ===${NC}"
echo "=== Now open vim and run :VundleInstall to install all plugins"
echo "=== Once installed Go binary, run in vim: :GoInstallBinaries and :GoUpdateBinaries"
echo -e "${GREEN}=== FINISH! ===${NC}"

