#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

usage() {
    echo -e "${RED}$0 must be run as root ${NC}"
    exit 1
}

if [ $UID -ne 0 ]; then 
    usage
fi

echo -e "${GREEN}=== INSTALLING i3 DEPS and UTILITIES... ${NC}"

apt-get install alsa-utils feh pavucontrol lxappearance wicd wicd-gtk

echo -e "${GREEN}=== FINISH! ===${NC}"
