#!/bin/bash

if [[ $UID -ne 0 ]]; then
    echo "$0 must be run as root"
    exit 1
fi

echo "=== INSTALLING FLASH PLAYER..."
add-apt-repository ppa:skunk/pepper-flash
echo "repository added!"
apt-get update -y
echo "update"
add-apt-repository ppa:skunk/pepper-flash
echo "Flash player installed"
echo "=== FINISH!"
