#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

usage() {
    echo -e "${RED}$0 must be run as root${NC}"
    exit 1
}

if [ $UID -ne 0 ]; then
    usage
fi

echo -e "${GREEN}=== INSTALLING DEPENDENCIES ===${NC}"
apt-get install lm-sensors curl hddtemp -y
echo "=== Setting up sensors..."
sensors
echo "=== Installing conky..."
apt-get install conky-all -y
echo "=== Coping rc file..."
cp ../conky/.conkyrc ~
chown -R andrea:andrea ~/.conkyrc
echo -e "${GREEN}=== FINISH! ===${NC}"




