#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

if [ $UID -ne 0 ]; then
    echo -e "${RED}$0 must be run as root${NC}"
    exit 1
fi

#
# https://www.sublimetext.com/docs/3/linux_repositories.html
#

echo -e "${GREEN}=== INSTALLING SUBLIME-TEXT...${NC}"

echo "=== Obtaining GPG key ..."
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -

echo "=== Adding new source in /etc/apt/sources.list.d/sublime-text.list ..."
echo "deb https://download.sublimetext.com/ apt/stable/" | \\
tee /etc/apt/sources.list.d/sublime-text.list

echo "=== Updating Sources ..."
apt-get update

echo -e "${GREEN}=== Now installing...${NC}"
apt-get install sublime-text 
echo -e "${GREEN}=== FINISH!${NC}"

