#!/bin/bash

if [[ $UID -ne 0 ]]; then
    echo "$0 must be run as root"
    exit 1
fi

if [[ $# < 3 || $# > 4 ]]; then
    echo "Not enough arguments!"
    echo "Use: $0 normal-user github-username github-email"
    exit 1
fi

user=$1
NAME=$2
EMAIL=$3

echo "=== INSTALL AND CONFIGURE GIT..."
apt-get install git -y
git config --global user.name "${NAME}"
echo "Git user.name as ${NAME}"
git config --global user.email ${EMAIL}
chown ${user}:${user} ~/.gitconfig
echo "Git user.email as ${EMAIL}"
echo "=== FINISH!"
