#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

if [ $UID -ne 0 ]; then
    echo -e "${RED}$0 must be run as root${NC}"
    exit 1
fi

echo -e "${GREEN}=== INSTALLING UBUNTU UTILITY PACKAGES...${NC}"
apt-get install vim htop wget vlc build-essential gparted keepassx tcptrack \
    thunderbird iotop filezilla djmount scrot wavemon libcrack2 nmap ffmpeg \
    gimp gpicview -y

echo -e "${GREEN}=== INSTALLING ARCHIVE MANAGERS TOOLS...${NC}"
apt-get install zip unzip tar rar xarchiver

echo -e "${GREEN}=== INSTALLING AVAHI-DAEMON AND TOOLS...${NC}"
apt-get install avahi-daemon avahi-discover avahi-utils libnss-mdns mdns-scan

echo "=== Coping htoprc... "
mkdir $HOME/.config/htop
cp ../htop/htoprc $HOME/.config/htop
echo "=== DONE!"

echo -e "${GREEN}=== INSTALLING FUNNY STUFF...${NC}"
apt-get install figlet cowsay sl -y
echo -e "${GREEN}=== FINISH! ===${NC}"
