#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

if [ $UID -ne 0 ]; then
    echo -e "${RED}$0 must be run as root${NC}"
    exit 1
fi

DEB='XnViewMP-linux-x64.deb'
LINK='http://download.xnview.com/'

echo -e "${GREEN}=== INSTALLING XNVIEW...${NC}"

echo -e "=== Downloading ${DEB}"
wget $LINK$DEB

echo -e "${GREEN}=== Now installing...${NC}"
dpkg -i $DEB

echo -e "${GREEN}=== Removing .deb file...${NC}"
rm $DEB

echo -e "${GREEN}=== FINISH!${NC}"

