#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

usage(){
    echo -e "${RED}Usage: $0 <workspace/absolute/path>${NC}"
    exit -1
}

[[ $# -eq 0 ]] && usage

echo -e "${GREEN}=== Golang Workspace initiate in $1 ${NC}"
mkdir -p $1/bin
mkdir -p $1/pkg
mkdir -p $1/src/github.com/AndreaGhizzoni
echo -e "${GREEN}=== Workspace created in $1${NC}"

