#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

# usage: ./install_from_source <version> <os> <arch> <folder>
usage() {
    echo -e "${RED}Usage: $0 <version> <os> <arch> </workspace/absolute/path>${NC}"
    exit 1
}

if [ $UID -eq 0 ]; then
    echo -e "${RED}This script must be run as normal user.${NC}"
    exit 1
fi

[[ $# -eq 0 ]] && usage
# check if version is set
[[ -z "$1" ]] && usage 
# check if os is set
[[ -z "$2" ]] && usage
# check if arch is set
[[ -z "$3" ]] && usage
# check if workspace path is set
[[ -z "$4" ]] && usage

# 1.8, 1.7...
VERSION=$1
# linux, windows ..
OS=$2
# amd64, i386
ARCH=$3
# default location
DST="/usr/local"
GOROOT="$DST/go"
# workspace path
GOPATH=$4

if [ -d "$GOROOT" ]; then
    echo -e "${GREEN}=== Folder ${GOROOT} already present on the system.${NC}" 
    echo -e "${GREEN}=== Proceeding to remove it... (sudo password may be required).${NC}" 
    sudo rm -rf ${GOROOT}
    echo -e "${GREEN}=== Old folder removed.${NC}" 
fi

echo -e "${GREEN}=== Downloading new go archive in ${DST} (sudo password may be required)...${NC}" 
GOTAR="go${VERSION}.${OS}-${ARCH}.tar.gz"
sudo wget -P ${DST} https://storage.googleapis.com/golang/${GOTAR}

echo -e "${GREEN}=== Extracting go archive...${NC}" 
sudo tar -C ${DST} -xzf ${DST}/${GOTAR}
sudo chown -R andrea:andrea ${GOROOT}

echo -e "${GREEN}=== Removing go archive...${NC}" 
sudo rm ${DST}/${GOTAR}

./create_workspace ${GOPATH}

echo -e "${GREEN}=== FINISH!${NC}" 
echo "=== Remember to add the following lines to your .profile" 
echo "export GOOS=${OS}"
echo "export GOARCH=${ARCH}"
echo "export GOROOT=${GOROOT}"
echo "export PATH=\$PATH:\$GOROOT/bin"
echo "export GOPATH=${GOPATH}"
echo "export PATH=\$PATH:\$GOPATH/bin"
