# ================ COMPILER
#GCC=gcc
#CPP=g++

# ================ COMPILER OPTIONS
#CFLAGS=-Wall -ansi -pedantic-errors -faggressive-loop-optimizations -O2
#CPPFLAGS= -DEVAL -O2 -std=c++0x

# ================ FOLDERS
#BIN=bin
#SRC=src
#INCLUDE=include
#TEST=test

# ================ RULES
# default option to make 
default: 

# get a description of makefile
description:

# generate bin files
bin: clearbin

# runs the tests
runtests: bin

#TODO check if bin exists
clearbin:
	$(RM) 
