#GCC=gcc
#CPP=g++
#SRCIN=
#SRCOUT=
#OUT=
#IN=
#ODIR=obj
#SDIR=src
#CFLAGS=-Wall -ansi -pedantic-errors -faggressive-loop-optimizations -O2
#CPPFLAGS= -DEVAL -O2 -std=c++0x

# default option to make 
default : 

compileall :

run :

clear :
	$(RM)
