#!/bin/bash

if [[ $UID -ne 0 ]]; then
    echo "$0 must be run as root"
    exit 1
fi

NAME="AndreaGhizzoni"
EMAIL="andrea.ghz@gmail.com"

echo "=== Installing and configure git..."
yum install git -y
git config --global user.name "${NAME}"
echo "Git user.name as ${NAME}"
git config --global user.email ${EMAIL}
echo "Git user.email as ${EMAIL}"
echo "=== Finish!"
