#!/bin/bash

if [[ $UID -ne 0 ]]; then
    echo "$0 must be run as root"
    exit 1
fi

V=$(rpm -E %fedora)
FREE="http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-${V}.noarch.rpm"
NFREE="http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${V}.noarch.rpm"

echo "=== Installing RPM FUSION FREE and NON_FREE..."
yum localinstall --nogpgcheck ${FREE} ${NFREE}
echo "=== Finish!"
