#!/bin/sh

# instructions taken from: https://golang.org/doc/install/source

# usage: ./go_install_from_source <version> <folder>
usage() {
    echo "Usage: ./$0 goX /installation/path"
    echo "Where X is the Go version to install/update from repository."
    echo "The installation path must be absolute (suggestion: /usr/local )."
    exit 1
}

requirements(){
    echo "This script requires: git"
    echo "Install all the requirements and run this again."
    exit 1
}

[[ $# -eq 0 ]] && usage
[[ -z "$1" ]] && usage
[[ -z "$2" ]] && usage

# ==== REQUIREMENTS ====
# check if git is installed
command -v git >/dev/null 2>&1 || { requirements }

# this must be goX where X is a go version: 1.8, 1.7...
VERSION=$1

# this must be an absolute path.
DST=$2
GO="go"
GO_ROOT="$DST/$GO"

# if $GO_ROOT exists then update the content
if [ -d "$GO_ROOT" ]; then
    cd $GO_ROOT/src
    git fetch 
    git checkout $VERSION
else
    # check if $GOROOT_BOOTSTRAP is set
    if [ -z "$GOROOT_BOOTSTRAP" ]; then
        wget https://storage.googleapis.com/golang/go1.4-bootstrap-20161024.tar.gz \
            /tmp
        cd /tmp
        tar -xzf go1.4-bootstrap-20161024.tar.gz 
        cd go/src
        ./make.bash

        GOROOT_BOOTSTRAP=/tmp/go
        export GOROOT_BOOTSTRAP
    fi
    cd $DST
    sudo git clone https://go.googlesource.com/go $GO
    sudo chown andrea:andrea -R $GO
    cd $GO
    git checkout $VERSION 
    cd src
fi

./all.bash

# echo a reminder to set:
# $GOROOT
# $GOPATH
# $GOARCH
# $GOOS

