#!/bin/bash

echo "===== INSTALLING FLUX"
wget -c http://justgetflux.com/linux/xflux64.tgz
tar -xvzf xflux64.tgz
rm -rf xflux64.tgz
chmod +x xflux
sudo mv xflux /usr/bin
echo "===== xflux starting at startup"
cp xflux.desktop ~/.config/autostart/
echo "===== FINISH!"
