#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
    echo " ${BATTERY_POWER}%"
    echo " ${BATTERY_POWER}%"
    echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
    if [[ $BATTERY_POWER -ge 90 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -ge 75 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -ge 50 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -le 20 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo "#FFAE00"
    fi

    if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
        notify-send -u critical "Battery Low"
        exit 33
    fi
else
    echo "No Battery"
    echo "No Battery"
    echo ""
fi


