#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
    echo " ${BATTERY_POWER}%"
    echo " ${BATTERY_POWER}%"
    echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
    if [[ $BATTERY_POWER -ge 76 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -lt 75 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -lt 50 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo ""
    elif [[ $BATTERY_POWER -lt 25 ]]; then
        echo " ${BATTERY_POWER}%"
        echo " ${BATTERY_POWER}%"
        echo "#FFAE00"
    fi
else
    echo "unknow state"
    echo "unknow state"
    echo ""
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
    notify-send -u critical "Battery Low"
    exit 33
fi
